QUICKBOOKS_APPLICATION_NAME = 'quickbooks-sync'
QUICKBOOKS_CUSTOMER_NAME_LEN_MAX = 41
QUICKBOOKS_VENDOR_NAME_LEN_MAX = 41
QUICKBOOKS_MEMO_LEN_MAX = 4095
QUICKBOOKS_SEPARATOR = ' - '
INTEUM_DSN = 'inteumCSdb'
